In [1]:
import pandas as pd

In [5]:
dataset = pd.read_csv("dataset_marks.csv")

In [7]:
dataset

Name  Hours  Marks
0  Rahul      4     40
1   Eric      6     60
2   Yash      8     80
3  Harry      3     30

In [11]:
dataset["Marks"]

0    40
1    60
2    80
3    30
Name: Marks, dtype: int64

In [13]:
y = dataset["Marks"]

In [15]:
dataset["Hours"]

0    4
1    6
2    8
3    3
Name: Hours, dtype: int64

In [17]:
x = dataset["Hours"]

In [22]:
y  # target and dependent variable

0    40
1    60
2    80
3    30
Name: Marks, dtype: int64

In [26]:
x  # independent variable

0    4
1    6
2    8
3    3
Name: Hours, dtype: int64

In [28]:
# From the above case study we have identified that this is a Linear Regression problem

In [30]:
# The only game of Machine Learning is to find the coefficient 'c'. Means we have to find that how much of x is impacting the y.

In [32]:
# For Linear Regression we use 'scikit-learn' library.

In [34]:
from sklearn.linear_model import LinearRegression

In [46]:
model = LinearRegression()


# This function will help us to create the model and to train the model we need data

In [50]:
model.fit(x,y)

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [52]:
x.values

array([4, 6, 8, 3], dtype=int64)

In [56]:
X = x.values.reshape(4,1)

In [58]:
X

array([[4],
       [6],
       [8],
       [3]], dtype=int64)

In [60]:
model.fit(X,y)

LinearRegression()

In [70]:
model.predict([[5]])

array([50.])

In [72]:
model.coef_

array([10.])

In [74]:
# Saving the model 

In [76]:
import joblib

In [78]:
joblib.dump(model, "marks_predictor.model")

['marks_predictor.model']